# id: 1
server:
  address: "server:12345"
loop:
  lapse: "0m20s"
  period: "5s"
log:
  level: "info"
bet:
  name: "Francisco"
  surname: "Pereira"
  id: "41797243"
  birthdate: "1998-12-17"
  beted_number: 4567
dataset:
  path: "./dataset/agency"
batch_size: 1000